server:
  port: 8080
  servlet:
    context-path: /

spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  flyway:
    locations:
      - classpath:db/migration
    user: test
    password: test

application:
  server:
    error:
      verbose: true

springdoc:
  swagger-ui:
    path: /doc
    queryConfigEnabled: true
  api-docs:
    path: /api-doc-inventory